requests-cache/aiohttp-client-cache

- aiohttp_client_cache/__init__.py
- aiohttp_client_cache/response.py
Fixes #1.
The main issue was that the response history was being saved as a generator, and that we weren't awaiting the recursive call. This basically caused everything to break when trying to cache a response with any history at all. While fixing this, I also noticed that there are cases where the encoding is null even after the response has been read and released. (In particular, I observed this situation on the actual `ClientResponse` objects that were present in the history itself.) This PR should solve the issue and support caching responses with histories.
> fix(history): Fix pickling issue when response history is non-null

- aiohttp_client_cache/backends/mongo.py
Hi, me again :-) just a quick PR to implement `contains` for `MongoDBCache`. Roughly tested it against my own application and all seems to work well.
> feat(mongo): Implement contains for mongo cache

- aiohttp_client_cache/__init__.py
- aiohttp_client_cache/backends/mongo.py
- setup.py
- test/backends/__init__.py
- test/backends/test_backend_mongo.py
I'm no expert on Motor (or Mongo in general), but thought I'd whip up this PR to try to add support for Motor to the MongoDB backend. I've also added in some kind-of-unit-tests.
The tests require a mongo server running locally in order to work; since this may not always be the case/feasible, I've added support for an environment variable, `BACKENDS_TO_TEST`, which is a space-delimited list of backends that should be tested. That means, by default, the Mongo backend tests won't be run.
I've also never used pytest before, so let me know if the testing pattern I've used could be improved upon.
I've implemented `MongoDBCache.values` here as well, though I wasn't sure about the desired semantics, so let me know if the implementation needs to change. 
One question: I haven't used Python's new …
> feat(mongo): Use Motor as MongoDB client, add some (unit-ish) tests, implement `values`

- aiohttp_client_cache/response.py
- test/unit/test_response.py
Closes #28 
`CachedResponse` now stores raw headers (which are directly serialized), and returns headers as a `CIMultiDictProxy` with a property (which is not serialized). Uses the same decoding as [aiohttp.http_parser.HeadersParser.parse_headers()](https://github.com/aio-libs/aiohttp/blob/64fd941091f1c24b78aa5c2114e389ac2dcdeeb5/aiohttp/http_parser.py#L123-L214).
> Support case-insensitive response headers for compatibility with aiohttp.ClientResponse.headers

- .github/workflows/build.yml
- .readthedocs.yml
- CONTRIBUTING.md
- README.md
- aiohttp_client_cache/backends/base.py
- docker-compose.yml
- docs/Dockerfile
- docs/conf.py
- docs/index.rst
- setup.py
* Update dependencies due to changes in docutils
* Switch docs to Material theme
* Use url-normalize to normalize URLs when creating cache keys
* Add some more details to Readme and Contributing Guide
* Update CI config to combine test coverage reports with other tests, so we don't need to spin up integration test databases for multiple jobs
* Add docker-compose config for httpbin
* And add docker-compose config for readthedocs build environment
> Documentation & CI updates

- aiohttp_client_cache/backends/base.py
Sorry, I neglected to return here but had meant to. Without this, there's a misleading "Cached response expired" log message, and an unnecessary call to delete.
> fix: short circuit get_response when no resp found

- .github/workflows/build.yml
- README.md
- aiohttp_client_cache/backends/dynamodb.py
- setup.py
- test/integration/test_dynamodb_backend.py
Draft PR to raise some questions I had while starting to work on this.
The minimal integration tests work for me if I run the dynamodb local service, but I have to run that as root to workaround perms issues sqlite raises when trying to write to the mounted volume. I'm not sure if this is specific to my setup.
I'll raise other questions inline.
> async impl of DynamoDBBackend

- CONTRIBUTING.md
- HISTORY.md
- aiohttp_client_cache/backends/base.py
- aiohttp_client_cache/backends/mongo.py
- aiohttp_client_cache/cache_keys.py
- aiohttp_client_cache/expiration.py
- aiohttp_client_cache/response.py
- aiohttp_client_cache/session.py
- pyproject.toml
- test/integration/test_cache.py
- test/integration/test_mongo_backend.py
- test/integration/test_redis_backend.py
- test/integration/test_sqlite_backend.py
- test/unit/test_base_backend.py
- test/unit/test_expiration.py
- test/unit/test_response.py
Closes #45 , and does some of the prep work needed for #30 and #32.
Other changes:
* Move all expiration logic into a separate module, and add more tests
* If `expire_after` is numeric, expect in in seconds instead of hours (for consistency with Cache-Control)
* Add some more unit test coverage for CacheBackend
> Add support for per-request expiration

- CONTRIBUTING.md
- HISTORY.md
- aiohttp_client_cache/backends/base.py
- aiohttp_client_cache/cache_control.py
- aiohttp_client_cache/session.py
- docs/reference.rst
- docs/user_guide.rst
- test/conftest.py
- test/integration/test_cache.py
- test/unit/test_base_backend.py
- test/unit/test_cache_control.py
- test/unit/test_response.py
- test/unit/test_session.py
Updates #30, closes #58, and makes handling request headers possible for #32. 
The class will be responsible for translating CacheBackend settings and request + response headers into specific actions to take for a given cache item. This will be convenient for reducing shared logic between request and response headers, and reducing arguments passed between functions (mainly between `get_reponse()` and `save_response()`).
I was originally just going to do some refactoring, but at this point the following items were pretty trivial so I went ahead and added them:
* Add support for `max-age`, `no-cache`, and `no-store` request headers
* Add support for `Expires` response header
> Refactor utilities for resolving expiration settings + headers into a separate class

- .github/workflows/build.yml
- HISTORY.md
- aiohttp_client_cache/backends/base.py
- aiohttp_client_cache/cache_keys.py
- aiohttp_client_cache/session.py
- test/unit/test_base_backend.py
- test/unit/test_cache_keys.py
This fix ensures that any equivalent variations on a URL and request parameters result in the same cache key.
> Fix url & request param normalization

- aiohttp_client_cache/response.py
- test/integration/base_backend_test.py
> Fix looping over streaming responses with readany()

- .github/workflows/build.yml
- .pre-commit-config.yaml
- HISTORY.md
- aiohttp_client_cache/session.py
- poetry.lock
- pyproject.toml
- test/unit/test_session.py
> Fix compatibility with aiohttp 3.8

- HISTORY.md
- aiohttp_client_cache/session.py
- test/unit/test_session.py
Partial fix for #100. This does not yet fully handle cookies set within a redirect chain.
> Add support for cached session cookies

- pyproject.toml
These end up getting installed if packaged in the (root of the) wheel.
> Only package Markdown and YAML files in sdist

- HISTORY.md
- aiohttp_client_cache/response.py
- aiohttp_client_cache/session.py
- test/conftest.py
- test/unit/test_session.py
Fixes #110:
* Initializes `CachedResponse.cookies` to an empty dict if not present
* Handles case when `CachedResponse.cookies == None` on a previously cached response
* **Note:** `aiohttp.abc.AbstractCookieJar.update_cookies()` does not handle `None`, and raises a `TypeError`
> Fix issue with restoring empty session cookies

- docs/user_guide.md
'CacheBackend' object has no attribute 'urls'
API reference[1] clearly contradicts what was written in the user guide
[1] https://aiohttp-client-cache.readthedocs.io/en/latest/modules/aiohttp_client_cache.backends.base.html#aiohttp_client_cache.backends.base.CacheBackend.get_urls
> Fix get_urls() example

- HISTORY.md
- aiohttp_client_cache/backends/base.py
- aiohttp_client_cache/session.py
- poetry.lock
- pyproject.toml
- test/unit/test_base_backend.py
Closes #93 
Basically this just requires these changes for `CacheBackend.save_response()`:
1. Don't require a `CacheActions` object
2. Generate a cache key if one isn't provided
So something like this is now possible:
```python
from aiohttp_client_cache import CachedSession, SQLiteBackend
async with CachedSession() as session:
response = await session.get('http://httpbin.org/get')
await session.cache.save_response(response)
```
> Support manually saving a response to the cache

- HISTORY.md
- aiohttp_client_cache/backends/base.py
- aiohttp_client_cache/session.py
- test/unit/test_base_backend.py
- test/unit/test_response.py
This PR adds support for async filter functions, as described in #121 . Some simple unit tests have been added to check that async filtering works and that the change is backwards compatible.
Unrelated to the core theme of the PR, it also cleaned up a unit test that was timing dependent (expiration test) and failed sometimes based on execution timings. This should now run regardless of actual execution time.
It should be noted that I haven't run any integration tests, but I feel like this shouldn't break much.
> Add support for async filter functions

- .pre-commit-config.yaml
- aiohttp_client_cache/backends/sqlite.py
- poetry.lock
- pyproject.toml
- test/conftest.py
- test/integration/base_backend_test.py
Fixes #127.
* A lock is used in the SQLite backend mainly to prevent multiple connections from performing certain write operations at the same time
* Update with `threading.RLock` instead of `asyncio.Lock`
* Only use lock for `init_db()` and `clear()`
> Fix delete_expired_responses() with SQLite backend

- .github/workflows/build.yml
- .github/workflows/deploy.yml
- .pre-commit-config.yaml
- HISTORY.md
- aiohttp_client_cache/__init__.py
- aiohttp_client_cache/backends/base.py
- aiohttp_client_cache/backends/redis.py
- aiohttp_client_cache/cache_control.py
- aiohttp_client_cache/cache_keys.py
- aiohttp_client_cache/response.py
- aiohttp_client_cache/session.py
- aiohttp_client_cache/signatures.py
- poetry.lock
- pyproject.toml
- setup.cfg
- test/unit/test_base_backend.py
Fixes #140
* Fix AttributeError when using a response cached with an older version of attrs
* Update dependencies and pre-commit hooks
* Update CI image and poetry versions
* Fix implicit Optional type errors with latest mypy version
> Fix attrs compatibility issue

- .github/workflows/build.yml
- HISTORY.md
- aiohttp_client_cache/backends/redis.py
- aiohttp_client_cache/backends/sqlite.py
- noxfile.py
- test/conftest.py
- test/integration/base_backend_test.py
- test/integration/test_filesystem.py
- test/integration/test_redis.py
- test/integration/test_sqlite.py
Closes #136.
So far, it seems that with `aiosqlite` it's fine to leave an open connection without ever explicitly closing it (same behavior as stdlib `sqlite3`).
There are some differences, though. For example, it manages its own thread for running queries, and its `connect()` function is a layer of abstraction that proxies real `sqlite3` connection objects. So there may be some other potential issues I haven't thought of yet.
> Reuse SQLite connection objects

- HISTORY.md
- aiohttp_client_cache/__init__.py
- aiohttp_client_cache/backends/base.py
- aiohttp_client_cache/backends/sqlite.py
- aiohttp_client_cache/session.py
- pyproject.toml
- test/integration/base_backend_test.py
- test/integration/base_storage_test.py
- test/integration/test_filesystem.py
- test/integration/test_mongodb.py
- test/integration/test_sqlite.py
> Close database connections (if applicable) on CachedSession.__aexit__

- aiohttp_client_cache/backends/base.py
- aiohttp_client_cache/backends/dynamodb.py
- aiohttp_client_cache/backends/filesystem.py
- aiohttp_client_cache/backends/mongodb.py
- aiohttp_client_cache/backends/redis.py
- aiohttp_client_cache/backends/sqlite.py
Type checkers expect function params to be fully typed in strict mode. Pyright is particular in also expecting `kwargs` to be annotated.
> Improve backend public types

- HISTORY.md
- aiohttp_client_cache/backends/base.py
- aiohttp_client_cache/backends/redis.py
- aiohttp_client_cache/backends/sqlite.py
- aiohttp_client_cache/session.py
- aiohttp_client_cache/signatures.py
- test/integration/base_backend_test.py
- test/integration/test_sqlite.py
Closes #153. Also see https://github.com/requests-cache/aiohttp-client-cache/discussions/146
This is enabled by default only for the SQLite backend.
> Add autoclose option to close backend when session closes

- .github/workflows/build.yml
- .pre-commit-config.yaml
- HISTORY.md
- aiohttp_client_cache/backends/__init__.py
- aiohttp_client_cache/backends/mongodb.py
- poetry.lock
- test/unit/test_session.py
Fixes #167
* Pass through all kwargs if superclass init accepts variable keyword args
* pymongo makes things difficult by both accepting `**kwargs` and validating them later, so make an exception for MongoDB backend
> Add compatibility with Sentry SDK

- aiohttp_client_cache/backends/filesystem.py
FileBackend is using SQLiteCache for redirects and this must be closed in CachedSession() context manager to avoid a deadlock.
This simple script was hanging for me:
```import asyncio
from datetime import timedelta
from aiohttp_client_cache import CachedSession, FileBackend
async def main():
cache = FileBackend(cache_name='.some_cache',
expire_after=timedelta(days=1))
async with CachedSession(cache=cache) as session:
async with session.disabled():
await session.get("https://www.google.fr")
if __name__ == "__main__":
asyncio.run(main(), debug=True)
```
Without this patch, one would have to explicitly call cache.close() to avoid the deadlock.
> backends/filesystem: set autoclose to True by default.

- aiohttp_client_cache/backends/dynamodb.py
The `context` argument for `DynamoDBBackend` was missing a type hint.
> Add optional type hint for DynamoDB context

- aiohttp_client_cache/backends/filesystem.py
- test/integration/test_filesystem.py
> Fix storage location of redirect database for FileBackend cache.

- aiohttp_client_cache/backends/base.py
- aiohttp_client_cache/cache_control.py
- aiohttp_client_cache/session.py
- test/integration/base_backend_test.py
- test/integration/test_filesystem.py
This fixes #182 .
The proposed fix takes the disabled status of the CachedSession into account when the necessary CacheActions are determined from the request. I tried to follow the existing logic which already includes skip read / write. This could also be solved differently, but I would consider this to be a clean solution.
> Take disabled status of CachedSession for CacheActions

- aiohttp_client_cache/backends/filesystem.py
- test/integration/base_backend_test.py
- test/integration/test_filesystem.py
This fixes #178 .
In the test_gather method, I added an additional semaphore to limit the maximum number of concurrent requests to 100 as I was getting "too many files open" errors when running the test in my environment (I have maximum number of open files set to 1024). This can be removed as it depends on the environment.
The fix for the test_gather method was to ensure that when opening a nonexistent cache file for a given key, None is returned. Tbh I dont fully understand why this is needed as there the _try_io should catch all exceptions, but apparently something internal to asyncio was not working as expected afterwards.
> Unit test fixes for FileBackend.

- test/integration/base_storage_test.py
- test/integration/test_redis.py
- test/integration/test_sqlite.py
This PR fixes a few further unit test problems that I encountered:
-  gather method for redis backend works fine, so enabled the test
-  ensure files generated during test are created in tmp directory
- ensure that all method calls during test execution happen within a context manager to properly close the cache (otherwise a sqlite connection hangs around in some cases)
With all these fixes, running all tests in my IDE successfully completes without any hanging thread.
> Further unit test fixes

- aiohttp_client_cache/response.py
- test/unit/test_response.py
Add attribute `closed` to `CachedResponse` for compatibility to work with `aiohttp-try`. Fix #191
> Add attribute `closed` to `CachedResponse`

- aiohttp_client_cache/backends/sqlite.py
- noxfile.py
- poetry.lock
- pyproject.toml
- test/integration/base_backend_test.py
- test/integration/test_memory.py
- test/integration/test_sqlite.py
- test/unit/test_base_backend.py
Here is one possible solution for #187. This works based on the logic of [`aiosqlite.Connection.run()`](https://github.com/omnilib/aiosqlite/blob/40442815b1a9a67b6f458fe56a1f4717c6f6c74c/aiosqlite/core.py#L76-L109) (implementation of `Thread.run()`). It can be forced to exit without blocking or scheduling any tasks by setting an internal flag and emptying its task queue. The underlying `sqlite3.Connection` object will not be closed (which is a blocking operation), but in my experience this doesn't cause any problems.
This will only be used in the case where the `SQLiteCache` object is being garbage-collected and the connection has not yet been closed implicitly (via contextmanager exit) or explicitly (via `close()`).
This does have the potential for data loss, if somehow the session or …
> Close SQLite connection if session is deleted and thread is still running

- aiohttp_client_cache/backends/base.py
- aiohttp_client_cache/cache_control.py
- aiohttp_client_cache/session.py
- examples/github.py
- test/integration/base_backend_test.py
This PR adds support for conditional requests.
I extracted the relevant code in a separate method so that I can check in a test whether it was called with mocking.
However, it would be great if httpbin would support an endpoint to changes its etag over time. Will look into that and provide a patch there so we can use it here as well if accepted.
This fixes #79 .
Code cov needs to be improved though.
> Support for conditional requests

- .pre-commit-config.yaml
- HISTORY.md
- aiohttp_client_cache/backends/dynamodb.py
- poetry.lock
- test/integration/test_dynamodb.py
> Handle responses that exceed DynamoDB max item size

- .github/workflows/build.yml
- aiohttp_client_cache/backends/redis.py
- test/conftest.py
- test/integration/test_redis.py
There are various exceptions during test execution when run on python 3.11:
These seems to be related to this issue:
https://github.com/python/cpython/issues/109538
This PR adds the workaround as described in the ticket.
> Fix exceptions encountered during tests with python 3.11

- .github/workflows/build.yml
- docker-compose.yml
- test/conftest.py
See https://docs.docker.com/engine/security/rootless/#networking-errors
When running the Docker daemon as a non-root user (Rootless mode), executing `docker compose up` will give an error similar to
```
cannot expose privileged port 80
```
There are multiple ways to solve this. All are mentioned in the official Docker docs, see the link above.
On my opinion, the simplest non-breaking solution is to use a non-privileged port by default. 
Additionally, the current solution even extends developer's possibilities: a developer can specify a custom port via `HTTPBIN_CUSTOM_PORT` environment variable before running  `docker compose up`.
No.
No.
> fix: use an unprivileged port for a server

- aiohttp_client_cache/response.py
```
mypy.....................................................................Failed
- hook id: mypy
- exit code: 1
aiohttp_client_cache/response.py:136: error: Cannot override writeable attribute with read-only property  [override]
aiohttp_client_cache/response.py:136: error: Signature of "_headers" incompatible with supertype "HeadersMixin"  [override]
aiohttp_client_cache/response.py:136: note:      Superclass:
aiohttp_client_cache/response.py:136: note:          MultiMapping[str]
aiohttp_client_cache/response.py:136: note:      Subclass:
aiohttp_client_cache/response.py:136: note:          CIMultiDictProxy[str]
Found 2 errors in 1 file (checked 38 source files)
```
Based on the code, I decided that you override a returned type intentionally, so instead of changing a type I suppressed a …
> fix: suppress Mypy error

- .github/workflows/build.yml
- HISTORY.md
- README.md
- aiohttp_client_cache/__init__.py
- docs/user_guide.md
- poetry.lock
- pyproject.toml
- test/conftest.py
- test/integration/base_backend_test.py
- test/integration/test_sqlite.py
- test/unit/test_base_backend.py
Updates #164
This mostly just updates docs and tests, not the actual library code.
> Drop support for python 3.7

- .pre-commit-config.yaml
- aiohttp_client_cache/cache_control.py
As a part of work on https://github.com/requests-cache/aiohttp-client-cache/issues/164, I added https://github.com/asottile/pyupgrade with the target Python version defined as `3.8`.
I did make unrelated changes (any Python 3.7 leftovers, if any, should removed in a separate PR).
No.
Not required.
`HISTROY.md` already has a related record: https://github.com/requests-cache/aiohttp-client-cache/blame/main/HISTORY.md#L5
---
I think that the next step is removing Black, Flake8, Isort, pyupgrade because Ruff re-implemented all of them. Similar to https://github.com/requests-cache/requests-cache/commit/83f7bc77e4daeab70e19e29a1ed1ba4bcabff9e1 but in that PR you replaced only Flake8.
> Add "pyupgrade" pre-commit hook and auto-format the code accordingly

- poetry.lock
- pyproject.toml
https://python-poetry.org/docs/managing-dependencies/#dependency-groups
> Poetry will slowly transition away from the dev-dependencies notation which will soon be deprecated, so it’s advised to migrate your existing development dependencies to the new group notation.
You can put this PR on hold if someone still needs to use Poetry 1.2 for some reason, but also if someone has multiple versions installed.
> chore: migrate outdated Poetry config [ci skip]

- aiohttp_client_cache/cache_control.py
- poetry.lock
- pyproject.toml
- test/unit/test_cache_control.py
- Now it is clear what is and is not accepted by the function.
- Previously, `float` and `bool` could be silently converted to `None`. Since this is not safe and does not match the function description, `float` and `bool` are now not accepted.
- Added a test. 
No.
Sadly, `|` and `typing.Union` are unsupported with `@singledispatch` in older Python versions. I had to downgrade the code and use a much longer syntax.
> Make `try_int` safer and add a test for it

- aiohttp_client_cache/session.py
Typechecking complaint about it being ClientSession, so override it to return CachedSession itself.
Or is it intentional to return it as ClientSession?
> Override __aenter__ for CachedSession

- aiohttp_client_cache/response.py
- pyproject.toml
No
I looked at https://github.com/requests-cache/aiohttp-client-cache/commit/e43d75148ce5edcd52356e4985c27d0af855a300 where you added 
```py
if isinstance(client_response, cls):
return client_response
```
but I was not able to reproduce why or when these lines can be triggered or used.
I will update in a next PR.
I was going to include `check_untyped_defs = true` in this PR, but it raises too many warnings, so I prefer to create a dedicated PR.
> Update Mypy config and type annotations

- aiohttp_client_cache/backends/base.py
- aiohttp_client_cache/session.py
- test/integration/base_backend_test.py
- test/unit/test_session.py
With this change if there is simultaneous request to the same url at the same time, it will only fetch the url once and the rest is feeded from cache
@olk-m @JWCook 
I create a test like this, is it enogh?
> Add asyncio.Lock mutex to _request 

- HISTORY.md
- aiohttp_client_cache/backends/sqlite.py
- poetry.lock
- pyproject.toml
- test/integration/test_sqlite.py
> Fix compatibility with aiosqlite 0.20

- HISTORY.md
- aiohttp_client_cache/cache_control.py
- aiohttp_client_cache/response.py
- pyproject.toml
- test/integration/base_backend_test.py
- test/unit/test_cache_control.py
- test/unit/test_response.py
Fixes #237; related to #195
Note: a future improvement would be to start using timezone-aware datetime objects, but this will cause problems with existing cache data (can't compare timezone-aware and timezone-naive datetimes). It would be best to do this at the same time as a release that includes changes to request matching logic (i.e., new cache keys).
>  Remove usage of `datetime.utcnow()` (deprecated in python 3.12)

- HISTORY.md
- aiohttp_client_cache/response.py
- test/unit/test_response.py
Thanks to @alessio-locatelli for pointing this out [here](https://github.com/requests-cache/aiohttp-client-cache/commit/2fa1b3926f78c145b826729333aa568cc4eac186#diff-b18bf159d5926d2ff91d8d8023250f2adf80ec7101a5e800a2055f16041ebbd4R138).
> Fix error case in `CachedResponse.is_expired`

- aiohttp_client_cache/__init__.py
- docs/conf.py
- poetry.lock
- pyproject.toml
Fix for this docs build failure: https://readthedocs.org/projects/aiohttp-client-cache/builds/25756437/
> Fix sphinx-automodapi patch to work with v0.18

- HISTORY.md
- aiohttp_client_cache/response.py
- test/unit/test_response.py
This PR closes https://github.com/requests-cache/aiohttp-client-cache/pull/286
As I explained on that page:
1. `convert_to_utc_naive()`  is not called for low-level API and it is a user responsibility to convert to a naive datetime. On our side we can raise an error.
2. `save_response()` and `from_client_response()` allow to save any random object as `expires`, including classes, functions, etc. and all these bad things work silently.
An alternative solution is moving `convert_to_utc_naive()` call inside the `from_client_response()`.
---
Notes:
```
except (AttributeError, TypeError, ValueError):
```
1. `AttributeError` is impossible because `self.expires = None` is the default class attribute.
3. `TypeError` is handled now by verifying that we work with a naive datetime.
4. `ValueError` - …
> Forbid wrong 'expires' values when low-level API is used that silently results in always expired responses

- HISTORY.md
- aiohttp_client_cache/backends/base.py
- aiohttp_client_cache/backends/sqlite.py
- docs/backends.md
Closes https://github.com/requests-cache/aiohttp-client-cache/issues/241
```py
import asyncio
from aiohttp_client_cache import CachedSession, SQLiteBackend
cache = SQLiteBackend(cache_name="./test_cache.sqlite")
async def task(n: int):
url = f"https://httpbin.org/ip?count={n}"
async with CachedSession(cache=cache) as session:
return await session.get(url, ssl=False)
async def tasks(arr: list):
tasks = [task(i) for i in arr]
return await asyncio.gather(*tasks)
asyncio.run(tasks(list(range(10))))
```
We can see the warning inside `get_connection()` **after** the `yield`:
```py
❯ python .gather_sessions.py
/usr/lib64/python3.13/contextlib.py:221: UserWarning: Cache access after closing the `Cachedsession` context manager is discouraged and can be forbidden in the future to prevent errors …
```
> Show a warning on a cache access when a `CachedSession` context manager has been exited

- HISTORY.md
- aiohttp_client_cache/response.py
- test/integration/base_backend_test.py
Closes https://github.com/requests-cache/aiohttp-client-cache/issues/289
- `ClientResponse` allows to call `read()` multiple times, returning a full content.
- `CachedResponse` allows to call `read()` multiple times, but silently returns nothing on further calls.
@JWCook  Would you mind sharing your viewpoint? If this behavior is intentional, I will update the test accordingly.  
---
**UPDATE 2024-10-30:**   
I do not know if anyone ever calls `read()` more than once, so you may want to keep this change unreleased for a while or create a pre-release.
> Fix `CachedResposnse.read()` and `ClientResponse.read()` consistency

- .pre-commit-config.yaml
- HISTORY.md
- aiohttp_client_cache/backends/sqlite.py
- pyproject.toml
- test/integration/base_backend_test.py
- test/integration/test_sqlite.py
(probably) fixes #330.
The main change is to set a single (unconnected) `aiosqlite.Connection` object on both `responses` and `redirects` during init. When the first request is made, `SQLiteBackend.responses.get_connection()` will open the connection.
This depends on the fact that `aiosqlite.connect()` isn't actually a coroutine, but a wrapper that returns a `Thread` subclass that also implements an [`__await__`](https://github.com/omnilib/aiosqlite/blob/main/aiosqlite/core.py#L138-L140) method that starts the thread. There are some more details in the comments. This requires checking some of aiosqlite's internal attributes, which I don't love, but at the moment it seems like the least messy option.
Let me know if anyone has suggestions for better ways to go about it!
> Share aiosqlite connection and async lock used by SQLite backend

- HISTORY.md
- aiohttp_client_cache/response.py
- test/unit/test_response.py
Closes https://github.com/requests-cache/aiohttp-client-cache/issues/350
@YisusChrist please review.
> fix: use request headers in `CachedResponse.request_info`

- aiohttp_client_cache/response.py
- aiohttp_client_cache/session.py
- poetry.lock
- pyproject.toml
Adds `typing-extensions>=4` for Python before 3.11 for the `Self` type, too.
Closes https://github.com/requests-cache/aiohttp-client-cache/issues/352
> Type hinting `__aenter__` with `Self`
