requests-cache/aiohttp-client-cache

README.md
aiohttp_client_cache/backends/base.py
aiohttp_client_cache/backends/sqlite.py
aiohttp_client_cache/response.py
aiohttp_client_cache/session.py
test/unit/test_base_backend.py
test/unit/test_response.py

Add support for URL pattern-based expiration

---

aiohttp_client_cache/backends/base.py

As per suggestion https://github.com/JWCook/aiohttp-client-cache/pull/37/files/4f1669a46a96eceeae68c10dd2f61531d4afa072#r604346762 , this proposes calling the cache's read method firstly in the default backend's get_response method instead of calling contains. This avoids a potentially expensive lookup for remote caches with no downside of which I'm aware.

call cache read directly instead of checking contains

---

HISTORY.md
aiohttp_client_cache/backends/base.py
aiohttp_client_cache/backends/gridfs.py
aiohttp_client_cache/backends/mongo.py
aiohttp_client_cache/backends/redis.py
aiohttp_client_cache/backends/sqlite.py
test/integration/test_cache.py
test/integration/test_mongo_backend.py
test/integration/test_redis_backend.py
test/integration/test_sqlite_backend.py
test/unit/test_base_backend.py

Remaining type errors for `DynamoDBBackend` are fixed in #37.

Convert all keys() and values() methods into async generators

---

HISTORY.md
aiohttp_client_cache/backends/sqlite.py
test/integration/test_sqlite_backend.py

Add use_temp option to SQLite backend

---

HISTORY.md
aiohttp_client_cache/response.py
test/unit/test_response.py

Fix handling of CachedResponse.encoding when the response body is None

---

.github/workflows/build.yml
HISTORY.md
aiohttp_client_cache/__init__.py
aiohttp_client_cache/backends/__init__.py
aiohttp_client_cache/backends/filesystem.py
aiohttp_client_cache/session.py
docs/backends.md
poetry.lock
pyproject.toml

Add a filesystem backend

---

HISTORY.md
aiohttp_client_cache/cache_keys.py
test/unit/test_cache_keys.py

Fix handling of request body when it has already been serialized

---

HISTORY.md
aiohttp_client_cache/response.py
pyproject.toml
test/integration/base_backend_test.py
test/unit/test_response.py

Add support for streaming requests

---

aiohttp_client_cache/response.py
examples/log_requests.py

Make CachedResponse.content a settable property

---

HISTORY.md
aiohttp_client_cache/backends/base.py
test/integration/base_backend_test.py

Fix Cache-Control checks getting enabled by default

---

HISTORY.md
aiohttp_client_cache/__init__.py
aiohttp_client_cache/cache_keys.py
pyproject.toml
test/unit/test_cache_keys.py

Fix issue with request params duplicated from request URL

---

aiohttp_client_cache/backends/base.py
aiohttp_client_cache/backends/dynamodb.py
aiohttp_client_cache/backends/filesystem.py
aiohttp_client_cache/backends/mongodb.py
aiohttp_client_cache/backends/redis.py
aiohttp_client_cache/backends/sqlite.py
test/integration/base_storage_test.py
test/integration/test_dict.py

ENH: Adds bulk_delete methods

---

.gitignore
.pre-commit-config.yaml
HISTORY.md
aiohttp_client_cache/response.py
poetry.lock
test/unit/test_response.py

Add HeadersMixin to provide additional properties derived from headers

---

.gitignore
HISTORY.md
poetry.lock
pyproject.toml

Remove upper version constraint for attrs dependency

---

.github/workflows/build.yml
HISTORY.md
aiohttp_client_cache/backends/mongodb.py
docker-compose.yml
test/integration/test_dynamodb.py
test/integration/test_mongodb.py

Fix passing connection parameters to MongoDB backend

---

.github/workflows/build.yml
.github/workflows/deploy.yml
HISTORY.md
aiohttp_client_cache/backends/base.py
aiohttp_client_cache/backends/dynamodb.py
aiohttp_client_cache/backends/filesystem.py
aiohttp_client_cache/backends/mongodb.py
aiohttp_client_cache/backends/redis.py
aiohttp_client_cache/backends/sqlite.py
aiohttp_client_cache/signatures.py
docs/conf.py
poetry.lock
pyproject.toml

Remove most usage of python-forge and make it a doc dependency only

---

docs/conf.py
poetry.lock
pyproject.toml

Reference: https://github.com/pradyunsg/furo/discussions/693

Fix issue with furo and sphinx 7.2.1/6.2.1

---

HISTORY.md
aiohttp_client_cache/backends/mongodb.py

Very minor performance tweaks. 
Alongside with a title, every commit has a body with an explanation.
No.
No.

Optimize MongoDB usage

---

aiohttp_client_cache/session.py
pyproject.toml

Added two options that are useful and can not break something.

Update Mypy config

---

.github/workflows/deploy.yml
.pre-commit-config.yaml
CONTRIBUTING.md
HISTORY.md
poetry.lock

Added some notes on steps needed to publish a new release.
@olk-m Let me know if you think this needs any more details.
Would you like to handle the next release? If so, I'm fine with publishing v0.11 anytime now, just give me a couple days notice so I can help if anything goes wrong.
No obligation to keep doing that going forward, I mainly want to test if the release steps are easy enough for other devs to understand. And no rush, we can wait on that if there are other changes you'd like to like to get done first.

Add notes about releases to contributing guide

---

HISTORY.md
aiohttp_client_cache/response.py
test/integration/base_backend_test.py

- Ideally, I need to publish a package after merging.
- Optionally, you can yank `v0.12.0` on pypi.

Restore "request_info" property

---

aiohttp_client_cache/backends/sqlite.py
docs/backends.md

---
_CI is skipped because the change is too small and obvious, and I linted it locally with `pre-commit`._

docs: mention `autoclose=False`

---

aiohttp_client_cache/cache_control.py
test/unit/test_cache_control.py

In case of using the same pattern/url for other things.

Make sure the pattern accepts str and URL.
